# Generated by Django 5.2.10 on 2026-01-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_image_url_remove_book_tags_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Fantasy', 'Fantasy'), ('Science', 'Science'), ('History', 'History'), ('Mystery', 'Mystery'), ('Moshten', 'Moshten'), ('JENA_MI', 'JENA_MI')], max_length=50),
        ),
    ]
